#Requires -Version 5.1
<#
.SYNOPSIS
  WPF-based ITAM QR scanner for assigning NinjaOne devices to users.

.DESCRIPTION
  Standalone PowerShell WPF application that works with a USB barcode scanner
  (e.g. Eyoyo EYH2) to scan NinjaOne QR codes. The workflow is:

    1. Sign in to NinjaOne using OAuth Authorization Code + PKCE.
    2. Scan a user QR code  (URL: /#/userDashboard/{id}/overview).
    3. Scan one or more device QR codes (URL: /#/deviceDashboard/{id}/overview).
    4. Click "Assign" to set the user as the owner of all scanned devices.

  QR codes are generated by New-NinjaDeviceQRCode.ps1 and New-NinjaUserQRCode.ps1.

  The NinjaOne OAuth application must be configured as a Native (Authorization
  Code) type with redirect URI http://localhost (port-wildcard for native apps
  per RFC 8252).

.PARAMETER NinjaOneInstance
  NinjaOne instance hostname or base URL.
  Default: env:NINJA_BASE_URL or ca.ninjarmm.com.

.PARAMETER ClientId
  OAuth application Client ID.
  Default: env:NinjaOneClientId.

.EXAMPLE
  .\Invoke-NinjaITAMScanner.ps1

.EXAMPLE
  .\Invoke-NinjaITAMScanner.ps1 -NinjaOneInstance app.ninjarmm.com -ClientId "your-client-id"
#>

[CmdletBinding()]
param(
    [string] $NinjaOneInstance = $(if ($env:NINJA_BASE_URL) { $env:NINJA_BASE_URL } else { 'ca.ninjarmm.com' }),
    [string] $ClientId = $env:NinjaOneClientId
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName PresentationCore
Add-Type -AssemblyName WindowsBase

#region Script-Scope State
$script:AccessToken    = $null
$script:RefreshToken   = $null
$script:TokenExpiresAt = [datetime]::MinValue
$script:NinjaBaseUrl   = ''
$script:NinjaClientId  = ''
$script:UserInfo       = $null
$script:Devices        = [System.Collections.Generic.List[PSCustomObject]]::new()
$script:AuthPS         = $null
$script:AuthHandle     = $null
$script:AuthVerifier   = $null
$script:AuthRedirectUri = $null
$script:AuthListener   = $null
#endregion

#region Helper Functions
function Resolve-BaseUrl {
    param([string]$Instance)
    $u = $Instance.Trim()
    if ([string]::IsNullOrWhiteSpace($u)) { $u = 'https://app.ninjarmm.com' }
    if ($u -notmatch '^https?://') { $u = "https://$u" }
    return $u.TrimEnd('/')
}

function New-PkceVerifier {
    $buf = [byte[]]::new(48)
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return [Convert]::ToBase64String($buf) -replace '\+','-' -replace '/','_' -replace '=',''
}

function Get-PkceChallenge {
    param([string]$Verifier)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hash = $sha.ComputeHash([System.Text.Encoding]::ASCII.GetBytes($Verifier))
    return [Convert]::ToBase64String($hash) -replace '\+','-' -replace '/','_' -replace '=',''
}

function Test-TokenValid {
    return ($null -ne $script:AccessToken -and [datetime]::UtcNow -lt $script:TokenExpiresAt)
}

function Update-TokensFromResponse {
    param($Response)
    $script:AccessToken = $Response.access_token
    if ($Response.refresh_token) { $script:RefreshToken = $Response.refresh_token }
    $exp = if ($Response.expires_in) { [int]$Response.expires_in } else { 3600 }
    $script:TokenExpiresAt = [datetime]::UtcNow.AddSeconds($exp - 60)
}

function Invoke-TokenRefresh {
    if ([string]::IsNullOrWhiteSpace($script:RefreshToken)) {
        throw "No refresh token. Please sign in again."
    }
    $resp = Invoke-RestMethod -Uri "$($script:NinjaBaseUrl)/ws/oauth/token" -Method POST -UseBasicParsing -Headers @{
        'Accept'       = 'application/json'
        'Content-Type' = 'application/x-www-form-urlencoded'
    } -Body @{
        grant_type    = 'refresh_token'
        refresh_token = $script:RefreshToken
        client_id     = $script:NinjaClientId
    }
    Update-TokensFromResponse $resp
}

function Invoke-NinjaApi {
    param(
        [string]$Method = 'GET',
        [string]$Endpoint,
        [object]$Body
    )
    if (-not (Test-TokenValid)) { Invoke-TokenRefresh }
    $uri = "$($script:NinjaBaseUrl)/ws/api/v2/$($Endpoint.TrimStart('/'))"
    $p = @{
        Uri             = $uri
        Method          = $Method
        UseBasicParsing = $true
        ErrorAction     = 'Stop'
        Headers         = @{
            'Authorization' = "Bearer $($script:AccessToken)"
            'Accept'        = 'application/json'
        }
    }
    if ($Body -and $Method -ne 'GET') {
        $p.ContentType = 'application/json'
        $p.Body = ($Body | ConvertTo-Json -Depth 10)
    }
    return Invoke-RestMethod @p
}

function Find-UserById {
    param([int]$UserId)

    try {
        $allUsers = @(Invoke-NinjaApi -Endpoint 'users')
        $m = $allUsers | Where-Object { $_.id -eq $UserId } | Select-Object -First 1
        if ($m) {
            $n = (@($m.firstname, $m.lastname) | Where-Object { $_ }) -join ' '
            return [PSCustomObject]@{
                Id    = $m.id
                Uid   = if ($m.uid) { $m.uid } else { $m.id }
                Name  = if ($n) { $n } else { "User $UserId" }
                Email = $m.email
            }
        }
    } catch { }

    try {
        $allContacts = @(Invoke-NinjaApi -Endpoint 'contacts')
        $m = $allContacts | Where-Object { $_.id -eq $UserId } | Select-Object -First 1
        if ($m) {
            $n = (@($m.firstname, $m.lastname) | Where-Object { $_ }) -join ' '
            if (-not $n -and $m.name) { $n = $m.name }
            return [PSCustomObject]@{
                Id    = $m.id
                Uid   = if ($m.uid) { $m.uid } else { $m.id }
                Name  = if ($n) { $n } else { "Contact $UserId" }
                Email = $m.email
            }
        }
    } catch { }

    return $null
}

function Get-DeviceInfo {
    param([int]$DeviceId)
    $d = Invoke-NinjaApi -Endpoint "device/$DeviceId"
    $name = if ($d.displayName) { $d.displayName }
            elseif ($d.systemName) { $d.systemName }
            else { "Device $DeviceId" }
    return [PSCustomObject]@{
        Id   = $d.id
        Name = $name
    }
}

function Set-NinjaDeviceOwner {
    param([int]$DeviceId, $OwnerUid)
    Invoke-NinjaApi -Method POST -Endpoint "device/$DeviceId/owner/$OwnerUid"
}

function Get-QRData {
    param([string]$Text)
    $t = $Text.Trim()
    if ($t -match 'userDashboard/(\d+)')   { return @{ Type = 'user';   Id = [int]$Matches[1] } }
    if ($t -match 'deviceDashboard/(\d+)') { return @{ Type = 'device'; Id = [int]$Matches[1] } }
    return $null
}
#endregion

#region WPF XAML
$xaml = @"
<Window
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  Title="NinjaOne ITAM Scanner" Height="640" Width="560"
  WindowStartupLocation="CenterScreen" ResizeMode="CanResizeWithGrip"
  MinHeight="520" MinWidth="480">
  <Window.Resources>
    <Style TargetType="Button">
      <Setter Property="Padding" Value="12,6"/>
      <Setter Property="Margin" Value="4,2"/>
    </Style>
    <Style TargetType="GroupBox">
      <Setter Property="Margin" Value="0,0,0,8"/>
      <Setter Property="Padding" Value="4"/>
    </Style>
  </Window.Resources>
  <Grid Margin="16">
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="*"/>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>

    <TextBlock Grid.Row="0" FontSize="20" FontWeight="Bold" Margin="0,0,0,10"
               Text="NinjaOne ITAM Scanner"/>

    <Expander Grid.Row="1" x:Name="expSettings" Header="Connection Settings" Margin="0,0,0,8">
      <Border BorderBrush="#DDD" BorderThickness="0,1,0,0" Padding="8,10,8,4">
        <StackPanel>
          <Grid Margin="0,0,0,6">
            <Grid.ColumnDefinitions>
              <ColumnDefinition Width="80"/>
              <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <TextBlock VerticalAlignment="Center" Text="Instance"/>
            <TextBox Grid.Column="1" x:Name="tbInstance" Height="26"
                     VerticalContentAlignment="Center"/>
          </Grid>
          <Grid Margin="0,0,0,8">
            <Grid.ColumnDefinitions>
              <ColumnDefinition Width="80"/>
              <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <TextBlock VerticalAlignment="Center" Text="Client ID"/>
            <TextBox Grid.Column="1" x:Name="tbClientId" Height="26"
                     VerticalContentAlignment="Center"/>
          </Grid>
          <StackPanel Orientation="Horizontal">
            <Button x:Name="btnSignIn" Content="Sign In to NinjaOne" Width="170"/>
            <TextBlock x:Name="lblAuthStatus" VerticalAlignment="Center"
                       Margin="12,0,0,0" FontWeight="SemiBold"
                       Text="Not connected" Foreground="Gray"/>
          </StackPanel>
        </StackPanel>
      </Border>
    </Expander>

    <GroupBox Grid.Row="2" Header="Scanner Input">
      <TextBox x:Name="tbScannerInput" Height="28" FontSize="12"
               VerticalContentAlignment="Center" Margin="2"
               ToolTip="Focus this field, then scan a QR code. You can also paste a URL and press Enter."/>
    </GroupBox>

    <GroupBox Grid.Row="3" Header="Step 1 &#x2014; User">
      <Grid Margin="2">
        <Grid.ColumnDefinitions>
          <ColumnDefinition Width="*"/>
          <ColumnDefinition Width="Auto"/>
        </Grid.ColumnDefinitions>
        <TextBlock x:Name="lblUserInfo" TextWrapping="Wrap"
                   VerticalAlignment="Center" Foreground="Gray"
                   Text="No user scanned. Scan a user QR code to begin."/>
        <Button x:Name="btnClearUser" Grid.Column="1" Content="Clear"
                Visibility="Collapsed" VerticalAlignment="Center"/>
      </Grid>
    </GroupBox>

    <GroupBox Grid.Row="4" Header="Step 2 &#x2014; Devices">
      <DockPanel Margin="2">
        <StackPanel DockPanel.Dock="Bottom" Orientation="Horizontal" Margin="0,6,0,0">
          <TextBlock x:Name="lblDeviceCount" VerticalAlignment="Center"
                     Foreground="Gray" Text="0 devices scanned"/>
          <Button x:Name="btnRemoveDevice" Content="Remove Selected"
                  Margin="12,0,0,0" IsEnabled="False"/>
        </StackPanel>
        <ListBox x:Name="lbDevices" MinHeight="60"/>
      </DockPanel>
    </GroupBox>

    <StackPanel Grid.Row="5" Orientation="Horizontal"
                HorizontalAlignment="Center" Margin="0,0,0,8">
      <Button x:Name="btnAssign" Content="Assign All to User" Width="170"
              FontWeight="SemiBold" IsEnabled="False"/>
      <Button x:Name="btnReset" Content="Reset" Width="100"/>
    </StackPanel>

    <Border Grid.Row="6" Background="#F5F5F5" CornerRadius="4" Padding="8,6">
      <TextBlock x:Name="lblStatus" TextWrapping="Wrap" FontSize="12"
                 Text="Enter connection settings and sign in to begin."/>
    </Border>
  </Grid>
</Window>
"@
#endregion

#region Create Window and Bind Elements
$reader = New-Object System.Xml.XmlNodeReader ([xml]$xaml)
$window = [Windows.Markup.XamlReader]::Load($reader)

$tbInstance      = $window.FindName('tbInstance')
$tbClientId      = $window.FindName('tbClientId')
$btnSignIn       = $window.FindName('btnSignIn')
$lblAuthStatus   = $window.FindName('lblAuthStatus')
$expSettings     = $window.FindName('expSettings')
$tbScannerInput  = $window.FindName('tbScannerInput')
$lblUserInfo     = $window.FindName('lblUserInfo')
$btnClearUser    = $window.FindName('btnClearUser')
$lbDevices       = $window.FindName('lbDevices')
$lblDeviceCount  = $window.FindName('lblDeviceCount')
$btnRemoveDevice = $window.FindName('btnRemoveDevice')
$btnAssign       = $window.FindName('btnAssign')
$btnReset        = $window.FindName('btnReset')
$lblStatus       = $window.FindName('lblStatus')
#endregion

#region Initialize Defaults
$tbInstance.Text = $NinjaOneInstance
if ($ClientId) { $tbClientId.Text = $ClientId }
$hasDefaults = -not [string]::IsNullOrWhiteSpace($ClientId) -and -not [string]::IsNullOrWhiteSpace($NinjaOneInstance)
$expSettings.IsExpanded = -not $hasDefaults
#endregion

#region UI Helpers
function Update-ScanState {
    if ($null -eq $script:UserInfo) {
        $lblStatus.Text = 'Scan a user QR code (Step 1).'
        $btnAssign.IsEnabled = $false
    } elseif ($script:Devices.Count -eq 0) {
        $lblStatus.Text = "User: $($script:UserInfo.Name). Scan device QR codes (Step 2)."
        $btnAssign.IsEnabled = $false
    } else {
        $lblStatus.Text = "Ready to assign $($script:Devices.Count) device(s) to $($script:UserInfo.Name)."
        $btnAssign.IsEnabled = $true
    }
    $lblDeviceCount.Text = "$($script:Devices.Count) device(s) scanned"
    $btnRemoveDevice.IsEnabled = ($lbDevices.SelectedIndex -ge 0)
}

function Reset-All {
    $script:UserInfo = $null
    $script:Devices.Clear()
    $lbDevices.Items.Clear()
    $lblUserInfo.Text = 'No user scanned. Scan a user QR code to begin.'
    $lblUserInfo.Foreground = [System.Windows.Media.Brushes]::Gray
    $btnClearUser.Visibility = 'Collapsed'
    Update-ScanState
    $tbScannerInput.Clear()
    $tbScannerInput.Focus()
}

function Push-UIUpdate {
    $frame = [System.Windows.Threading.DispatcherFrame]::new()
    [System.Windows.Threading.Dispatcher]::CurrentDispatcher.BeginInvoke(
        [System.Windows.Threading.DispatcherPriority]::Background,
        [Action]{ $frame.Continue = $false }
    )
    [System.Windows.Threading.Dispatcher]::PushFrame($frame)
}
#endregion

#region Sign-In (Authorization Code + PKCE)
$btnSignIn.Add_Click({
    $script:NinjaBaseUrl  = Resolve-BaseUrl -Instance $tbInstance.Text
    $script:NinjaClientId = $tbClientId.Text.Trim()

    if ([string]::IsNullOrWhiteSpace($script:NinjaClientId)) {
        [System.Windows.MessageBox]::Show(
            'Client ID is required. Enter the Client ID from your NinjaOne OAuth application.',
            'Missing Client ID', 'OK', 'Warning') | Out-Null
        return
    }

    $btnSignIn.IsEnabled = $false
    $lblAuthStatus.Text = 'Waiting for browser sign-in...'
    $lblAuthStatus.Foreground = [System.Windows.Media.Brushes]::DarkOrange
    $lblStatus.Text = 'A browser window has been opened. Sign in to NinjaOne to continue.'
    Push-UIUpdate

    $script:AuthVerifier = New-PkceVerifier
    $challenge = Get-PkceChallenge -Verifier $script:AuthVerifier

    $port = Get-Random -Minimum 49152 -Maximum 65535
    $script:AuthRedirectUri = "http://localhost:$port/callback/"

    $script:AuthListener = [System.Net.HttpListener]::new()
    $script:AuthListener.Prefixes.Add($script:AuthRedirectUri)
    try {
        $script:AuthListener.Start()
    } catch {
        $lblAuthStatus.Text = 'Listener failed'
        $lblAuthStatus.Foreground = [System.Windows.Media.Brushes]::Red
        $lblStatus.Text = "Could not start local HTTP listener: $($_.Exception.Message)"
        $btnSignIn.IsEnabled = $true
        return
    }

    $authorizeUrl = "$($script:NinjaBaseUrl)/ws/oauth/authorize?" +
        "response_type=code" +
        "&client_id=$([uri]::EscapeDataString($script:NinjaClientId))" +
        "&redirect_uri=$([uri]::EscapeDataString($script:AuthRedirectUri))" +
        "&scope=monitoring%20management" +
        "&code_challenge=$challenge" +
        "&code_challenge_method=S256"

    Start-Process $authorizeUrl

    $script:AuthPS = [powershell]::Create()
    [void]$script:AuthPS.AddScript({
        param($lst)
        try {
            $ctx = $lst.GetContext()
            $q   = $ctx.Request.Url.Query
            $html = '<html><body style="font-family:system-ui,sans-serif;text-align:center;padding-top:60px">' +
                    '<h2>Authentication complete</h2>' +
                    '<p>You may close this tab and return to the ITAM Scanner.</p></body></html>'
            $buf = [System.Text.Encoding]::UTF8.GetBytes($html)
            $ctx.Response.ContentType    = 'text/html'
            $ctx.Response.ContentLength64 = $buf.Length
            $ctx.Response.OutputStream.Write($buf, 0, $buf.Length)
            $ctx.Response.Close()
            $lst.Stop()
            return $q
        } catch {
            try { $lst.Stop() } catch { }
            return "error=$($_.Exception.Message)"
        }
    }).AddArgument($script:AuthListener)

    $script:AuthHandle = $script:AuthPS.BeginInvoke()

    $timer = [System.Windows.Threading.DispatcherTimer]::new()
    $timer.Interval = [TimeSpan]::FromMilliseconds(500)
    $timer.Add_Tick({
        if (-not $script:AuthHandle.IsCompleted) { return }
        $this.Stop()

        try {
            $queryString = ($script:AuthPS.EndInvoke($script:AuthHandle) | Select-Object -First 1) -as [string]
            $script:AuthPS.Dispose()
            $script:AuthPS = $null

            if ($queryString -match '[?&]code=([^&]+)') {
                $code = [uri]::UnescapeDataString($Matches[1])
                $resp = Invoke-RestMethod `
                    -Uri "$($script:NinjaBaseUrl)/ws/oauth/token" `
                    -Method POST -UseBasicParsing `
                    -Headers @{
                        'Accept'       = 'application/json'
                        'Content-Type' = 'application/x-www-form-urlencoded'
                    } `
                    -Body @{
                        grant_type    = 'authorization_code'
                        code          = $code
                        redirect_uri  = $script:AuthRedirectUri
                        client_id     = $script:NinjaClientId
                        code_verifier = $script:AuthVerifier
                    }

                Update-TokensFromResponse $resp
                $lblAuthStatus.Text = 'Connected'
                $lblAuthStatus.Foreground = [System.Windows.Media.Brushes]::Green
                $expSettings.IsExpanded = $false
                $lblStatus.Text = 'Signed in successfully. Scan a user QR code to begin.'
                $tbScannerInput.Focus()
            }
            elseif ($queryString -match '[?&]error=([^&]+)') {
                $errMsg = [uri]::UnescapeDataString($Matches[1])
                $lblAuthStatus.Text = 'Failed'
                $lblAuthStatus.Foreground = [System.Windows.Media.Brushes]::Red
                $lblStatus.Text = "Sign-in failed: $errMsg"
            }
            else {
                $lblAuthStatus.Text = 'Failed'
                $lblAuthStatus.Foreground = [System.Windows.Media.Brushes]::Red
                $lblStatus.Text = 'Sign-in failed: no authorization code received.'
            }
        } catch {
            $lblAuthStatus.Text = 'Error'
            $lblAuthStatus.Foreground = [System.Windows.Media.Brushes]::Red
            $lblStatus.Text = "Authentication error: $($_.Exception.Message)"
        }
        $btnSignIn.IsEnabled = $true
    })
    $timer.Start()
})
#endregion

#region Scanner Input Processing
$tbScannerInput.Add_KeyDown({
    param($sender, $e)
    if ($e.Key -ne 'Return') { return }
    $e.Handled = $true
    $raw = $tbScannerInput.Text
    $tbScannerInput.Clear()

    if ([string]::IsNullOrWhiteSpace($raw)) { return }

    if (-not (Test-TokenValid) -and [string]::IsNullOrWhiteSpace($script:RefreshToken)) {
        $lblStatus.Text = 'Not signed in. Please sign in first.'
        [System.Media.SystemSounds]::Hand.Play()
        return
    }

    $qr = Get-QRData -Text $raw
    if (-not $qr) {
        $lblStatus.Text = 'Unrecognized QR code. Expected a NinjaOne userDashboard or deviceDashboard URL.'
        [System.Media.SystemSounds]::Hand.Play()
        return
    }

    if ($qr.Type -eq 'user') {
        $lblStatus.Text = "Looking up user $($qr.Id)..."
        Push-UIUpdate
        try {
            $userResult = Find-UserById -UserId $qr.Id
        } catch {
            $lblStatus.Text = "API error looking up user: $($_.Exception.Message)"
            [System.Media.SystemSounds]::Hand.Play()
            return
        }
        if (-not $userResult) {
            $lblStatus.Text = "User ID $($qr.Id) not found in NinjaOne users or contacts."
            [System.Media.SystemSounds]::Hand.Play()
            return
        }
        $script:UserInfo = $userResult
        $display = $userResult.Name
        if ($userResult.Email) { $display += "  ($($userResult.Email))" }
        $display += "  |  UID: $($userResult.Uid)"
        $lblUserInfo.Text = $display
        $lblUserInfo.Foreground = [System.Windows.Media.Brushes]::Black
        $btnClearUser.Visibility = 'Visible'
        [System.Media.SystemSounds]::Asterisk.Play()
        Update-ScanState
    }
    elseif ($qr.Type -eq 'device') {
        if ($null -eq $script:UserInfo) {
            $lblStatus.Text = 'Scan a user QR code first (Step 1) before scanning devices.'
            [System.Media.SystemSounds]::Hand.Play()
            return
        }
        if ($script:Devices | Where-Object { $_.Id -eq $qr.Id }) {
            $lblStatus.Text = "Device $($qr.Id) is already in the list."
            [System.Media.SystemSounds]::Exclamation.Play()
            return
        }
        $lblStatus.Text = "Looking up device $($qr.Id)..."
        Push-UIUpdate
        try {
            $deviceResult = Get-DeviceInfo -DeviceId $qr.Id
        } catch {
            $lblStatus.Text = "Device $($qr.Id) not found or API error: $($_.Exception.Message)"
            [System.Media.SystemSounds]::Hand.Play()
            return
        }
        $script:Devices.Add($deviceResult)
        $lbDevices.Items.Add("ID: $($deviceResult.Id)  |  $($deviceResult.Name)") | Out-Null
        [System.Media.SystemSounds]::Asterisk.Play()
        Update-ScanState
    }

    $tbScannerInput.Focus()
})
#endregion

#region Button Event Handlers
$btnClearUser.Add_Click({
    $script:UserInfo = $null
    $lblUserInfo.Text = 'No user scanned. Scan a user QR code to begin.'
    $lblUserInfo.Foreground = [System.Windows.Media.Brushes]::Gray
    $btnClearUser.Visibility = 'Collapsed'
    Update-ScanState
    $tbScannerInput.Focus()
})

$lbDevices.Add_SelectionChanged({
    $btnRemoveDevice.IsEnabled = ($lbDevices.SelectedIndex -ge 0)
})

$btnRemoveDevice.Add_Click({
    $idx = $lbDevices.SelectedIndex
    if ($idx -ge 0 -and $idx -lt $script:Devices.Count) {
        $script:Devices.RemoveAt($idx)
        $lbDevices.Items.RemoveAt($idx)
        Update-ScanState
    }
    $tbScannerInput.Focus()
})

$btnAssign.Add_Click({
    if ($null -eq $script:UserInfo -or $script:Devices.Count -eq 0) { return }

    $ownerUid = $script:UserInfo.Uid
    $total    = $script:Devices.Count
    $success  = 0
    $failed   = 0
    $errors   = [System.Collections.Generic.List[string]]::new()

    $btnAssign.IsEnabled = $false
    $btnReset.IsEnabled  = $false

    for ($i = 0; $i -lt $total; $i++) {
        $dev = $script:Devices[$i]
        $lblStatus.Text = "Assigning $($dev.Name) ($($i + 1)/$total)..."
        Push-UIUpdate

        try {
            Set-NinjaDeviceOwner -DeviceId $dev.Id -OwnerUid $ownerUid
            $success++
        } catch {
            $failed++
            $errors.Add("$($dev.Name) (ID $($dev.Id)): $($_.Exception.Message)")
        }
    }

    $summary = "Done. $success of $total device(s) assigned to $($script:UserInfo.Name)."
    if ($failed -gt 0) {
        $summary += " $failed failed."
        $detail = $summary + "`r`n`r`nErrors:`r`n" + ($errors -join "`r`n")
        [System.Windows.MessageBox]::Show($detail, 'Assignment Results', 'OK', 'Warning') | Out-Null
    } else {
        [System.Media.SystemSounds]::Asterisk.Play()
    }

    $lblStatus.Text = $summary
    $btnAssign.IsEnabled = $true
    $btnReset.IsEnabled  = $true
    $tbScannerInput.Focus()
})

$btnReset.Add_Click({
    Reset-All
})
#endregion

#region Window Events
$window.Add_ContentRendered({
    if (Test-TokenValid -or -not [string]::IsNullOrWhiteSpace($script:RefreshToken)) {
        $tbScannerInput.Focus()
    }
})

$window.Add_Activated({
    if ((Test-TokenValid -or -not [string]::IsNullOrWhiteSpace($script:RefreshToken)) `
        -and -not $expSettings.IsExpanded) {
        $tbScannerInput.Focus()
    }
})

$window.Add_Closing({
    if ($script:AuthListener -and $script:AuthListener.IsListening) {
        try { $script:AuthListener.Stop() } catch { }
    }
    if ($script:AuthPS) {
        try { $script:AuthPS.Stop() } catch { }
        try { $script:AuthPS.Dispose() } catch { }
    }
})
#endregion

#region Show Window (STA check)
if ([Threading.Thread]::CurrentThread.ApartmentState -ne 'STA') {
    $t = New-Object Threading.Thread({ $window.ShowDialog() | Out-Null })
    $t.SetApartmentState([Threading.ApartmentState]::STA)
    $t.Start()
    $t.Join()
} else {
    $window.ShowDialog() | Out-Null
}
#endregion
